resolver: lts-7.0

packages:
- '.'
- location:
    '../x/parsers'
  extra-dep: true
- location:
    'music-dynamics'
  extra-dep: true
- location:
    'music-pitch'
  extra-dep: true
- '../lilypond'

extra-deps:
- average-0.6.1
- data-interval-1.2.0
- positive-0.4.1
- prettify-1.0
- type-unary-0.2.21
- applicative-numbers-0.1.3
- extended-reals-0.2.1.0
- ty-0.1.7
- vector-space-points-0.2.1.2
  # for dev
